######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 26 23:17:56 2014
######################################################################

TEMPLATE = app
TARGET = animate_color
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cell.h
SOURCES += cell.cpp main.cpp
